### ISSUE TITLE
Vaadin 8 compatibility

### ISSUE THREAD

**Issue by clavaud** [alejandro-du/embedded-ui#2]
Dear,

We're currently trying to integrate Microservice with their own GUI, but facing some difficulties with Vaadin. 

I'm trying to use you component, but getting errors and I don't know if they are related to my usage or the incompatibility with Vaadin 8.

Could you help ?

Best regards

Alexandre

**Some code**
@SpringView(name = AdUserView.VIEW_NAME)
@UIScope
public class AdUserView extends VerticalLayout implements View {
	public static final String	VIEW_NAME			= "AdUserView";
	private static final long	serialVersionUID	= 1L;

	public AdUserView() {
		final VaadinUIComponent browser = new VaadinUIComponent( "http://localhost:8081/users/" );
		browser.setSizeFull();
		setSizeFull();
		addComponent( browser );

	}

	@Override
	public void enter(final ViewChangeListener.ViewChangeEvent event) {
		Notification.show( "AdUserView::Enter" );
	}
}

**Some errors when accessing remote app :** 
Mon Jun 12 11:22:57 GMT+000 2017 com.vaadin.client.communication.DefaultConnectionStateHandler
INFO: Reconnect attempt 781 for XHR
com.vaadin.DefaultWidgetSet-0.js:5848 Mon Jun 12 11:22:58 GMT+000 2017 com.vaadin.client.communication.DefaultConnectionStateHandler
INFO: Re-sending last message to the server...
com.vaadin.DefaultWidgetSet-0.js:5848 Mon Jun 12 11:22:58 GMT+000 2017 com.vaadin.client.communication.XhrConnection
INFO: Sending xhr message to server: {"csrfToken":"8165448b-f220-4325-b781-f8faba37ee4d","rpc":[["0","com.vaadin.shared.ui.ui.UIServerRpc","resize",[1029,393,1272,467]]],"syncId":0,"clientId":0,"wsver":"8.0.6"}
com.vaadin.DefaultWidgetSet-0.js:5541 POST http://localhost:8081/users/UIDL/?v-uiId=0 404 ()
Rs @ com.vaadin.DefaultWidgetSet-0.js:5541
aGb @ com.vaadin.DefaultWidgetSet-0.js:5668
gFb @ com.vaadin.DefaultWidgetSet-0.js:2928
CCb @ com.vaadin.DefaultWidgetSet-0.js:5495
dDb @ com.vaadin.DefaultWidgetSet-0.js:5849
Lb @ com.vaadin.DefaultWidgetSet-0.js:5847
(anonymous) @ com.vaadin.DefaultWidgetSet-0.js:2646
Rh @ com.vaadin.DefaultWidgetSet-0.js:2407
Uh @ com.vaadin.DefaultWidgetSet-0.js:4997
(anonymous) @ com.vaadin.DefaultWidgetSet-0.js:3507
com.vaadin.DefaultWidgetSet-0.js:5848 Mon Jun 12 11:22:58 GMT+000 2017 com.vaadin.client.communication.DefaultConnectionStateHandler
WARNING: Server returned 404 for xhr
eab @ com.vaadin.DefaultWidgetSet-0.js:5848
rFd @ com.vaadin.DefaultWidgetSet-0.js:5389
qFd @ com.vaadin.DefaultWidgetSet-0.js:3420
wFd @ com.vaadin.DefaultWidgetSet-0.js:3011
BFd @ com.vaadin.DefaultWidgetSet-0.js:2062
XCb @ com.vaadin.DefaultWidgetSet-0.js:5039
mGb @ com.vaadin.DefaultWidgetSet-0.js:5850
Ks @ com.vaadin.DefaultWidgetSet-0.js:3859
Xs @ com.vaadin.DefaultWidgetSet-0.js:5848
(anonymous) @ com.vaadin.DefaultWidgetSet-0.js:3489
Rh @ com.vaadin.DefaultWidgetSet-0.js:2407
Uh @ com.vaadin.DefaultWidgetSet-0.js:4997
(anonymous) @ com.vaadin.DefaultWidgetSet-0.js:3507
com.vaadin.DefaultWidgetSet-0.js:5848 Mon Jun 12 11:22:58 GMT+000 2017 com.vaadin.client.communication.DefaultConnectionStateHandler
INFO: Reconnect attempt 4 for XHR
``

**Comment by M0rfic** [comment]
Possibly related: https://stackoverflow.com/questions/45465131/embedding-vaadin-springboot-application-into-a-vaadin-ui-using-emdedded-ui-add/45496631#45496631

**Comment by alejandro-du** [comment]
Thanks for reporting. Please let me know if 2.1 fixes this.

**Comment by clavaud** [comment]
Dear, 

Works great for Vaadin 8, very good job. 

As I would like to migration my application to Vaadin 10, how to do the same thing with Vaadin 10 ... ? 

Best regards 

Alexandre

**Comment by alejandro-du** [comment]
There are no current plans to migrate this to Vaadin 10. Please "thumbs up" this issue if you are interested in having support for it in Vaadin Flow: https://github.com/vaadin/flow/issues/4316

**Comment by clavaud** [comment]
OK, then do you have any idea or tips on how to get the same behavior with Vaadin 10?
I have a microservice application with an ui for each service. I was using your component to federate all ui  in one application using a left menu go access microservice and the center page to display the remote ui... Using Vaadin 8, everything is working as expected, even using oauth2 (I did a change on your lib to handle it).

Thanks

Best regards

Alexandre

On 15 Aug 2018, at 10:27, Alejandro <notifications@github.com<mailto:notifications@github.com>> wrote:


There are no current plans to migrate this to Vaadin 10.

**Comment by alejandro-du** [comment]
You can try with iframes. And please upvote the referenced issue.
